# Generated by Django 2.2.1 on 2019-05-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='extid',
        ),
    ]
