# Generated by Django 2.2.1 on 2019-05-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_user_extid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='scale_id',
        ),
    ]
