# Generated by Django 2.1.3 on 2019-05-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_category_scale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Category'),
        ),
    ]
